### ISSUE TITLE
Consume classic realm status through Game Data API

### ISSUE THREAD

**Issue by viglucci** [EQdkpPlus/portal-realmstatus#9]
Please update the classic realm status module to consume the public Game Data API endpoints.

More information here: https://us.forums.blizzard.com/en/blizzard/t/world-of-warcraft-api-patch-notes-20200609/8902/1

**Comment by GodMod** [comment]
For the API, keys are required, which are not needed for the current version.

**Comment by viglucci** [comment]
@GodMod we would really rather you not consume the GraphQL API exposed on worldofwarcraft.com, and would prefer that you consume the public REST API exposed explicitely for this purpose.

I'm happy to address any of your concerns if you want to discuss challenges with doing so (@Maguthul over on [Discord](https://us.forums.blizzard.com/en/blizzard/t/community-discord-server/96/2) & on the API forums).

**Comment by GodMod** [comment]
Next time, please tell me that you are from Blizzard ;) I will change it to the API, but will take some time.

**Comment by viglucci** [comment]
Thanks for addressing the request :), and apologies for the confusion!

**Comment by GodMod** [comment]
A new version has been released, using the REST API now. Will take some time until the installations will update, but the requests to the GraphSQL API should decrease.

**Comment by viglucci** [comment]
Thank you @GodMod. We appreciate this request being completed in such a timely manner!
